### ISSUE TITLE
Using deprecated Pillow method tostring()

### ISSUE THREAD

**Issue by i-feofilaktov** [primetang/qrtools#2]
Got this problem when trying to use qrtools with up-to-date Pillow package (http://python-pillow.github.io/)

Traceback:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python2.7/dist-packages/qrtools.py:181: in decode
    raw = pil.tostring()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <PIL.Image.Image image mode=L size=128x128 at 0x7F1FAF783ED0>, args = ()
kw = {}

    def tostring(self, *args, **kw):
        raise Exception("tostring() has been removed. " +
>                       "Please call tobytes() instead.")
E       Exception: tostring() has been removed. Please call tobytes() instead.
```

Here's PIL function definition: https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L698

Here's my Pillow version:

```
$ pip show pillow 

---
Metadata-Version: 2.0
Name: Pillow
Version: 3.1.1
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.github.io/
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
Installer: pip
License: Standard PIL License
Location: /usr/local/lib/python2.7/dist-packages
```

It works with Pillow v.2.9.0

**Comment by Viatrak** [comment]
It looks like the repository source fixed this but it never got uploaded to pypi...

If you go into your dist-packages folder and open up qrtools.py you can search replace the one occurence of "tostring" to "tobytes" and it should work

**Comment by noraj** [comment]
You can find the probleme here :  https://bugs.launchpad.net/ubuntu/+source/python-qrtools/+bug/1574162

Just do that and upload to PyPi please

```
try:
    raw = pil.tobytes()
except AttributeError:
    raw = pil.tostring()
```

**Comment by primetang** [comment]
I have uploaded the new source to pypi. I'm sorry.
