### ISSUE TITLE
Why not import image from pillow by default.

### ISSUE THREAD

**Issue by blueforesticarus** [primetang/qrtools#3]
I was trying to get this library and its dependencies running on windows (unfortunately I had no choice) and I had to modify qrtools.py so that it imported from pillow by default.

Originally:

```
try:
    import Image
except:
    from PIL import Image
```

Changed To:

```
try:
    from PIL import Image
except:
    import Image
```

I had to do this because although "Image" could be imported without error it did not function as expected and caused qrtools to throw error when used. The image sub module of pillow, however, works perfectly. What is the reason for only using pillow as a fall back? Why not make pillow the default?

**Comment by primetang** [comment]
Have been changed!
